export const Logos = [
    {
      url: "/img/clientes/pan-american.svg",
      id: 1,
      name: "Pan American Energy",
      width: 115,
      height: 45,
    },
    {
      url: "/img/clientes/pluspetrol.png",
      id: 2,
      name: "Pluspetrol",
      width: 115,
      height: 45,
    },
    {
      url: "/img/clientes/tgs.svg",
      id: 3,
      name: "TGS",
      width: 97.5,
      height: 36,
    },
    {
      url: "/img/clientes/ypf.png",
      id: 4,
      name: "YPF",
      width: 85,
      height: 21,
    },
    {
      url: "/img/clientes/phoenix.png",
      id: 5,
      name: "Phoenix",
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/vista.svg",
      id: 6,
      name: "VISTA",  
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/cgc.png",
      id: 7,
      name: "CGC",  
      width: 60,
      height: 60,
    },
    {
      url: "/img/clientes/chevron.svg",
      id: 8,
      name: "Chevron",
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/pampa.png",
      id: 9,
      name: "Pampa Energía",
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/shell.svg",
      id: 10,
      name: "Shell",
      width: 63,
      height: 63,
    },
    {
      url: "/img/clientes/totalenergies.svg",
      id: 11,
      name: "TotalEnergies",  
      width: 73,
      height: 58,
    },
    {
      url: "/img/clientes/roch.png",
      id: 12,
      name: "Roch",
      width: 10,
      height: 65,
    },
    {
      url: "/img/clientes/wintershall.png",
      id: 13,
      name: "Wintershall Dea",  
      width: 105,
      height: 80,
    },
    {
      url: "/img/clientes/tgn.png",
      id: 14,
      name: "TGN",
      width: 117,
      height: 50,
    },
    {
      url: "/img/clientes/mega.png",
      id: 15,
      name: "MEGA",
      width: 116,
      height: 100,
    },
    {
      url: "/img/clientes/axion.png",
      id: 16,
      name: "AXION energy",
      width: 70,
      height: 82,
    },
    {
      url: "/img/clientes/refipampa.png",
      id: 17,
      name: "RefiPampa",
      width: 97,
      height: 16,
    },
    {
      url: "/img/clientes/air-liquide.svg",
      id: 18,
      name: "Air Liquide",
      width: 105,
      height: 20,
    },
    {
      url: "/img/clientes/transclor.png",
      id: 19,
      name: "Transclor",
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/atanor.png",
      id: 20,
      name: "Atanor",
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/saesa.png",
      id: 21,
      name: "SAESA",  
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/ypf-luz.png",
      id: 22,
      name: "YPF Luz",  
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/albanesi.png",
      id: 23,
      name: "Grupo Albanesi", 
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/galaxy.png",
      id: 24,
      name: "Galaxy Resources",   
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/allkem.png",
      id: 25,
      name: "Allkem",  
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/exar.png",
      id: 26,
      name: "EXAR",
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/litica.png",
      id: 27,
      name: "Litica Resources",
      width: 115,
      height: 49,
    },
    {
      url: "/img/clientes/lithium.png",
      id: 28,
      name: "Lithium Americas",
      width: 115,
      height: 49,
    },
  ];